//! Pasteboard save/restore around a paste. Runs on the main thread (callers use `on_main`).
//!
//! The dictated text is offered lazily through a data provider, so we learn when the target app
//! has read it and can put the previous contents back right after. It is also marked
//! `org.nspasteboard.TransientType` / `AutoGeneratedType`, which clipboard managers skip.

use std::cell::RefCell;
use std::sync::atomic::{AtomicBool, Ordering};
use std::time::{Duration, Instant};

use anyhow::{Result, bail};
use objc2::rc::Retained;
use objc2::runtime::{NSObject, NSObjectProtocol, ProtocolObject};
use objc2::{AllocAnyThread, DefinedClass, define_class, msg_send};
use objc2_app_kit::{
    NSPasteboard, NSPasteboardItem, NSPasteboardItemDataProvider, NSPasteboardType, NSPasteboardTypeString,
    NSPasteboardWriting,
};
use objc2_foundation::{NSArray, NSData, NSString};

const MARKER_TYPES: [&str; 2] = ["org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType"];

/// Set when the target app read the offered text.
static CONSUMED: AtomicBool = AtomicBool::new(false);

struct ProviderIvars {
    text: Retained<NSString>,
}

define_class!(
    #[unsafe(super(NSObject))]
    #[name = "DictumTextProvider"]
    #[ivars = ProviderIvars]
    struct TextProvider;

    unsafe impl NSObjectProtocol for TextProvider {}

    unsafe impl NSPasteboardItemDataProvider for TextProvider {
        #[unsafe(method(pasteboard:item:provideDataForType:))]
        fn provide(
            &self,
            _pasteboard: Option<&NSPasteboard>,
            item: &NSPasteboardItem,
            kind: &NSPasteboardType,
        ) {
            item.setString_forType(&self.ivars().text, kind);
            CONSUMED.store(true, Ordering::SeqCst);
        }
    }
);

impl TextProvider {
    fn new(text: &str) -> Retained<Self> {
        let this = Self::alloc().set_ivars(ProviderIvars { text: NSString::from_str(text) });
        unsafe { msg_send![super(this), init] }
    }
}

/// What was on the pasteboard: every item with every type it had.
type Items = Vec<Vec<(Retained<NSString>, Retained<NSData>)>>;

struct Pending {
    saved: Items,
    /// The pasteboard's change count once our text was on it.
    change_count: isize,
    /// Kept alive while the pasteboard may still ask it for the text.
    _provider: Retained<TextProvider>,
}

thread_local! {
    static PENDING: RefCell<Option<Pending>> = const { RefCell::new(None) };
}

fn general() -> Retained<NSPasteboard> {
    NSPasteboard::generalPasteboard()
}

fn write(pasteboard: &NSPasteboard, items: Vec<Retained<NSPasteboardItem>>) -> Result<()> {
    let objects: Vec<Retained<ProtocolObject<dyn NSPasteboardWriting>>> =
        items.into_iter().map(ProtocolObject::from_retained).collect();
    if !pasteboard.writeObjects(&NSArray::from_retained_slice(&objects)) {
        bail!("the pasteboard refused the data");
    }
    Ok(())
}

/// Puts plain text on the pasteboard for good (no restore).
pub fn set_text(text: &str) -> Result<()> {
    let pasteboard = general();
    pasteboard.clearContents();
    let item = NSPasteboardItem::new();
    item.setString_forType(&NSString::from_str(text), unsafe { NSPasteboardTypeString });
    write(&pasteboard, vec![item])
}

fn save(pasteboard: &NSPasteboard) -> Items {
    let Some(items) = pasteboard.pasteboardItems() else { return Vec::new() };
    items
        .iter()
        .map(|item| {
            item.types()
                .iter()
                .filter_map(|kind| item.dataForType(&kind).map(|data| (kind, data)))
                .collect::<Vec<_>>()
        })
        .filter(|types| !types.is_empty())
        .collect()
}

/// Saves the pasteboard and offers `text` in its place.
pub fn save_and_offer(text: &str) -> Result<()> {
    let pasteboard = general();
    let saved = save(&pasteboard);
    pasteboard.clearContents();
    let provider = TextProvider::new(text);
    let item = NSPasteboardItem::new();
    let types = NSArray::from_slice(&[unsafe { NSPasteboardTypeString }]);
    if !item.setDataProvider_forTypes(ProtocolObject::from_ref(&*provider), &types) {
        bail!("could not offer the text on the pasteboard");
    }
    let empty = NSData::new();
    for marker in MARKER_TYPES {
        item.setData_forType(&empty, &NSString::from_str(marker));
    }
    write(&pasteboard, vec![item])?;
    let change_count = pasteboard.changeCount();
    PENDING.with(|p| *p.borrow_mut() = Some(Pending { saved, change_count, _provider: provider }));
    Ok(())
}

/// Call right before pasting: reads from before don't count.
pub fn arm() {
    CONSUMED.store(false, Ordering::SeqCst);
}

/// Waits until the target app read the text. Returns `false` on timeout.
pub fn wait_consumed(timeout: Duration) -> bool {
    let deadline = Instant::now() + timeout;
    while !CONSUMED.load(Ordering::SeqCst) {
        if Instant::now() >= deadline {
            return false;
        }
        std::thread::sleep(Duration::from_millis(5));
    }
    true
}

/// Puts the saved contents back, unless something else changed the pasteboard meanwhile.
pub fn restore() -> Result<()> {
    let Some(pending) = PENDING.with(|p| p.borrow_mut().take()) else { return Ok(()) };
    let pasteboard = general();
    if pasteboard.changeCount() != pending.change_count {
        log::debug!("pasteboard changed after paste; not restoring");
        return Ok(());
    }
    pasteboard.clearContents();
    if pending.saved.is_empty() {
        return Ok(());
    }
    let items = pending
        .saved
        .iter()
        .map(|types| {
            let item = NSPasteboardItem::new();
            for (kind, data) in types {
                item.setData_forType(data, kind);
            }
            item
        })
        .collect();
    write(&pasteboard, items)
}
